#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const parser = require('../src/parser.js');
const Engine = require('../offline/engine.js');
const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'offline', 'data');
const SPECIALS = new Set(['stats', 'saves', 'restart', 'checkpoint_load', 'checkpoint_save']);

function emit(name, value) {
    const serialized = JSON.stringify(value).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
    fs.writeFileSync(path.join(OUTPUT, name + '.js'), '/* Generated by scripts/build-offline.cjs. */\n(function(g){g.MAGIUM_DATA=g.MAGIUM_DATA||{};g.MAGIUM_DATA[' + JSON.stringify(name) + ']=' + serialized + ';})(globalThis);\n');
}
function validate(scenes, filename, raw) {
    const totals = {set: 0, choice: 0, achievement: 0, if: 0};
    for (const scene of Object.values(scenes)) {
        totals.set += scene.setVariables.length;
        totals.choice += scene.choices.length;
        totals.achievement += scene.achievements.length;
        totals.if += scene.paragraphs.filter(p => p.conditions).length;
        for (const element of scene.setVariables.concat(scene.paragraphs, scene.choices)) {
            for (const group of element.conditions || []) for (const expression of group) Engine.condition(expression, {});
            if (element.special && !SPECIALS.has(element.special)) throw new Error('Unsupported special in ' + scene.id + ': ' + element.special);
        }
        for (const paragraph of scene.paragraphs) if (/(?:^|<br\/>)(?:choice\(|set\(|achievement\(|#if\()/.test(paragraph.text)) throw new Error('Unparsed control syntax in ' + scene.id);
    }
    for (const [name, count] of Object.entries(totals)) {
        const prefix = name === 'if' ? '#if(' : name + '(';
        const expected = raw.split(/\r?\n/).filter(line => line.startsWith(prefix)).length;
        if (expected !== count) throw new Error(filename + ': parser lost ' + name + ' entries (' + count + '/' + expected + ')');
    }
}
async function loadLocale(locale) {
    const directory = path.join(ROOT, 'data', locale), scenes = {};
    const files = fs.readdirSync(directory).filter(name => name.endsWith('.magium')).sort();
    for (const file of files) {
        const filename = path.join(directory, file);
        const parsed = await parser.parse(filename);
        validate(parsed, filename, fs.readFileSync(filename, 'utf8'));
        for (const [id, scene] of Object.entries(parsed)) {
            if (Object.prototype.hasOwnProperty.call(scenes, id)) throw new Error('Duplicate scene: ' + id);
            scene.source = file;
            scenes[id] = scene;
        }
    }
    for (const scene of Object.values(scenes)) for (const choice of scene.choices) {
        for (const target of [choice.target, choice.setVariables.v_current_scene]) if (target && !scenes[target]) throw new Error('Broken story link: ' + scene.id + ' -> ' + target);
    }
    const achievements = {};
    for (const book of [1, 2, 3]) achievements[book] = JSON.parse(fs.readFileSync(path.join(directory, 'achievements' + book + '.json'), 'utf8'));
    return {scenes, ui: JSON.parse(fs.readFileSync(path.join(directory, 'ui.json'), 'utf8')), achievements};
}
function storyLines(scene) {
    return scene.paragraphs.flatMap(p => p.text.split(/<br\s*\/?\s*>|\r?\n/i).map(text => text.trim()).filter(Boolean)).concat(scene.choices.map(c => c.text), scene.achievements.map(a => a.text));
}
function translationData(english) {
    const directory = path.join(ROOT, 'offline', 'locales');
    const files = fs.existsSync(directory) ? fs.readdirSync(directory).filter(name => /^zh-CN\.story(?:\..+)?\.json$/.test(name)).sort() : [];
    // Optional human-reviewed corrections have final precedence.
    if (fs.existsSync(path.join(directory, 'zh-CN.reviewed.json'))) files.push('zh-CN.reviewed.json');
    const translations = {};
    for (const file of files) {
        const payload = JSON.parse(fs.readFileSync(path.join(directory, file), 'utf8'));
        const map = payload.translations || payload;
        for (const [original, translated] of Object.entries(map)) {
            if (typeof translated !== 'string' || !translated.trim()) continue;
            // Align the agreed glossary across independently translated shards.
            const consistent = translated.replace(/莱萨(?:西|希|提)人/g, '莱萨提族').replace(/塞瑞石/g, '瑟瑞迪姆');
            translations[original] = consistent;
            translations[original.trim()] = consistent;
        }
    }
    const chapters = {}, all = new Set(), translated = new Set();
    for (const scene of Object.values(english.scenes)) {
        const position = Engine.chapter(scene.id), key = 'b' + position.book + 'ch' + position.chapter;
        if (!chapters[key]) chapters[key] = {book: position.book, chapter: position.chapter, units: new Set(), translated: new Set(), scenes: 0, completeScenes: 0};
        const group = chapters[key], lines = storyLines(scene);
        group.scenes++;
        if (lines.every(line => translations[line])) group.completeScenes++;
        for (const line of lines) {
            all.add(line); group.units.add(line);
            if (translations[line]) { translated.add(line); group.translated.add(line); }
        }
    }
    const coverage = {
        language: 'zh-CN', method: 'LLM translation; original English fallback for untranslated text',
        totalUnits: all.size, translatedUnits: translated.size,
        percent: Math.round(10000 * translated.size / all.size) / 100,
        chapters: Object.values(chapters).sort((a,b) => a.book - b.book || a.chapter - b.chapter).map(group => ({book: group.book, chapter: group.chapter, totalUnits: group.units.size, translatedUnits: group.translated.size, percent: Math.round(10000 * group.translated.size / group.units.size) / 100, scenes: group.scenes, completeScenes: group.completeScenes}))
    };
    const uiFile = path.join(directory, 'zh-CN.ui.json');
    const ui = fs.existsSync(uiFile) ? JSON.parse(fs.readFileSync(uiFile, 'utf8')) : {};
    Object.assign(ui, {
        settingsReadingModeText: '阅读样式',
        settingsReadingModeOriginalText: '原版',
        settingsReadingModeBookText: '书籍',
        settingsDialogueColorsText: '角色对白颜色',
        settingsDialogueColorsOffText: '关闭',
        settingsDialogueColorsOnText: '开启',
        settingsSemanticDialogueColorsText: '包含根据上下文推断的对白颜色',
        settingsAnimationEffectsText: '动画效果',
        settingsContextualTypographyText: '情境手稿字体'
    });
    return {translations, ui, coverage, sourceFiles: files};
}
async function build() {
    fs.rmSync(OUTPUT, {recursive: true, force: true});
    fs.mkdirSync(OUTPUT, {recursive: true});
    const en = await loadLocale('en'), fr = await loadLocale('fr');
    const zh = translationData(en);
    // These reviewed snapshots are deterministic build inputs. The large
    // intermediate scan/audit workspaces are intentionally excluded.
    const readingFile = path.join(ROOT, 'tools', 'reading-metadata', 'reading-enhancements.generated.json');
    const reading = JSON.parse(fs.readFileSync(readingFile, 'utf8'));
    const semanticReadingFile = path.join(ROOT, 'tools', 'reading-metadata', 'semantic-reading-enhancements.generated.json');
    const semanticReading = JSON.parse(fs.readFileSync(semanticReadingFile, 'utf8'));
    const documentTypographyFile = path.join(ROOT, 'tools', 'reading-metadata', 'document-typography.generated.json');
    const documentTypography = JSON.parse(fs.readFileSync(documentTypographyFile, 'utf8'));
    const recordCount = metadata => Object.values(metadata.locales.en.scenes)
        .reduce((sum, scene) => sum + scene.paragraphs.length, 0);
    emit('en', en); emit('fr', fr); emit('zh-CN', zh); emit('readingEnhancements', reading); emit('semanticReadingEnhancements', semanticReading); emit('documentTypography', documentTypography);
    const manifest = {format: 1, start: Engine.START, languages: ['en', 'fr', 'zh-CN'], scenes: Object.keys(en.scenes).length, choices: Object.values(en.scenes).reduce((sum, scene) => sum + scene.choices.length, 0), chapters: zh.coverage.chapters.length, translation: zh.coverage, readingEnhancements: {version: reading.version, speakers: Object.keys(reading.speakers).length, chapterOpenings: Object.keys(reading.chapterOpenings).length, semanticPairs: recordCount(semanticReading), documentTypographyRecords: recordCount(documentTypography)}};
    emit('manifest', manifest);
    require('./build-ui.cjs')({en,fr,'zh-CN':zh});
    fs.writeFileSync(path.join(OUTPUT, 'translation-coverage.json'), JSON.stringify(zh.coverage, null, 2) + '\n');
    console.log('Exported ' + manifest.scenes + ' scenes, ' + manifest.choices + ' English choices, ' + manifest.chapters + ' chapters. Chinese: ' + zh.coverage.translatedUnits + '/' + zh.coverage.totalUnits + ' text units (' + zh.coverage.percent + '%).');
    return {en, fr, 'zh-CN': zh, manifest};
}
if (require.main === module) build().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
module.exports = {build, loadLocale, translationData, storyLines, validate};
